### ISSUE TITLE
address already in use

### ISSUE THREAD

**Issue by jack-solutions** [XRFoundation/DigitalBeing#592]
No matter what it ends up with below error

python: __init__
Traceback (most recent call last):
  File "/home/lenovo/Desktop/Digital-Beings/server/grpc/handler.py", line 45, in __init__
    self.server = server('127.0.0.1', int(os.getenv('TCP_PORT')), self)
  File "/home/lenovo/Desktop/Digital-Beings/server/grpc/tcpServer.py", line 10, in __init__
    self._socket.bind((host, port))
OSError: [Errno 98] Address already in use

i am trying to run it with non docker method and when i do npm run start it ends up with above error. if someone could help me to run it that would be great!

**Comment by jack-solutions** [comment]
any one who can help?
